name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x, 21.x, 22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: install then test
      run: |
        yarn install
        echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
        echo '                       test'
        echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
        yarn test
